const ID = 0
const COUNT_PICTURES = 6
const MIN_COUNT_PICTURES = 0
const COUNT_COMMENTS = 5
const MIN_COUNT_COMMENTS = 0
const COUNT_AVATARS = 6
const MIN_AVATAR = 1
const MAX_AVATAR = 6
const MIN_COUNT_LIKES = 0
const MAX_COUNT_LIKES = 10

export {
    ID,
    COUNT_PICTURES,
    MIN_COUNT_PICTURES,
    COUNT_COMMENTS,
    MIN_COUNT_COMMENTS,
    COUNT_AVATARS,
    MIN_AVATAR,
    MAX_AVATAR,
    MIN_COUNT_LIKES,
    MAX_COUNT_LIKES,
}
